server:
  port: 8069

logging:
  level:
    root: WARN
    ru: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver


