server:
  port: 8069
  url: http://localhost:8068

logging:
  level:
    root: WARN
    ru: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


